services:
  postgresql:
    image: postgres:16-alpine
    restart: always
    environment:
      PGUSER: ${POSTGRES_USER:-postgres} # will use current os user otherwise.
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - ${POSTGRES_PORT:-2345}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    healthcheck:
      test: 'wget -O - http://127.0.0.1:1080/healthz || exit 1'

volumes:
  db:
    driver: local

# custom network to be able to reach Logto running on same network with another Docker Compose file
networks:
  logto_network:
    external: true
